#! /usr/bin/env python

import argparse
import musicbrainzngs
import discid

musicbrainzngs.set_useragent("Audacious", "0.1", "https://github.com/jonnybarnes/audacious")

parser = argparse.ArgumentParser()
parser.add_argument("--cdrom", help="provide the source of the cd", default="/dev/cdrom")
args = parser.parse_args()

device = args.cdrom

print("device: %s" % device)
disc = discid.read(device)
print("id: %s" % disc.id)

try:
	result = musicbrainzngs.get_releases_by_discid(disc.id, includes=["artists"])
except musicbrainzngs.ResponseError:
	print("disc not found or bad response")
else:
	if result.get("disc"):
		print("artist:\t%s" %
			result["disc"]["release-list"][0]["artist-credit-phrase"])
		print("title:\t%s" % result["disc"]["release-list"][0]["title"])
	elif result.get("cdstub"):
		print("artist:\t" % result["cdstub"]["artist"])
		print("title:\t" % result["cdstub"]["title"])