#! /usr/bin/env python

import os
import argparse
import musicbrainzngs
import discid

musicbrainzngs.set_useragent("Audacious", "0.1", "https://github.com/jonnybarnes/audacious")

parser = argparse.ArgumentParser()
parser.add_argument("--cdrom", help="provide the source of the cd", default="/dev/cdrom")
args = parser.parse_args()

device = args.cdrom

print("device: %s" % device)
disc = discid.read(device)
print("id: %s" % disc.id)

try:
	result = musicbrainzngs.get_releases_by_discid(disc.id, includes=["artists", "recordings"])
except musicbrainzngs.ResponseError:
	print("disc not found or bad response")
else:
	if result.get("disc"):
		artist = result["disc"]["release-list"][0]["artist-credit-phrase"]
		print("artist:\t%s" % artist)
		title = result["disc"]["release-list"][0]["title"]
		print("title:\t%s" % title)
		tracklist = result["disc"]["release-list"][0]["medium-list"][0]["track-list"]
	elif result.get("cdstub"):
		print("artist:\t" % result["cdstub"]["artist"])
		print("title:\t" % result["cdstub"]["title"])

print("Creating directories")
try:
	os.mkdir("./wav")
	os.mkdir("./mp3")
except FileExistsError:
	print("Directories already exist")